### ISSUE TITLE
In Lazy.css file i tried to change the      bg-primary{background-color:rgb(0, 0, 0) !important}        in black but it is not reflection in the app

### ISSUE THREAD

**Issue by yash-me** [bootstrapbay/lazy-kit-react#1]

**Comment by conacelelena** [comment]
Hello,

If you are using SCSS files, you need to make the change in the SCSS file _variables.scss for the $bg-primary variable. If you don't change this and only edit CSS, then your change will be overwritten when the SCSS gets compiled.

Let me know if this works for you.

All the best,
Cristina

**Comment by yash-me** [comment]
yeah It worked thanks aloot!

**Comment by conacelelena** [comment]
You're welcome ☺️
